In [1]:
import numpy as np
import pandas as pd

In [2]:
from tensorflow.keras import datasets

In [18]:
from tensorflow import keras

In [3]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_test.shape

(10000, 28, 28)

In [8]:
width, height = 28, 28
input_shape = (width, height, 1)

In [9]:
input_shape

(28, 28, 1)

In [10]:
x_train = x_train.reshape(x_train.shape[0], height, width, 1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

In [11]:
x_train.shape

(60000, 28, 28, 1)

In [12]:
y_train.shape

(60000,)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1)

In [14]:
len(x_val)

6000

In [15]:
x_train = (x_train - x_train.mean())/x_train.std()
x_test = (x_test - x_test.mean())/x_test.std()
x_val = (x_val - x_val.mean())/x_val.std()

In [16]:
x_train

array([[[[-0.42409178],
         [-0.42409178],
         [-0.42409178],
         ...,
         [-0.42409178],
         [-0.42409178],
         [-0.42409178]],

        [[-0.42409178],
         [-0.42409178],
         [-0.42409178],
         ...,
         [-0.42409178],
         [-0.42409178],
         [-0.42409178]],

        [[-0.42409178],
         [-0.42409178],
         [-0.42409178],
         ...,
         [-0.42409178],
         [-0.42409178],
         [-0.42409178]],

        ...,

        [[-0.42409178],
         [-0.42409178],
         [-0.42409178],
         ...,
         [-0.42409178],
         [-0.42409178],
         [-0.42409178]],

        [[-0.42409178],
         [-0.42409178],
         [-0.42409178],
         ...,
         [-0.42409178],
         [-0.42409178],
         [-0.42409178]],

        [[-0.42409178],
         [-0.42409178],
         [-0.42409178],
         ...,
         [-0.42409178],
         [-0.42409178],
         [-0.42409178]]],


       [[[-0.42409178],


In [17]:
y_train

array([0, 9, 8, ..., 4, 1, 8], dtype=uint8)

In [20]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [21]:
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [22]:
y_test = keras.utils.to_categorical(y_test)
y_val = keras.utils.to_categorical(y_val)

MODEL

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D

In [34]:
model = Sequential()
model.add(Conv2D(6, kernel_size = (5, 5), strides = (1,1), activation = 'tanh', input_shape = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2, 2), strides = (1,1)))    
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1,1), activation = 'tanh'))          
model.add(AveragePooling2D(pool_size = (2, 2), strides = (2,2))) 
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1,1), activation = 'tanh'))   
          
model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

In [35]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d_2 (Averag  (None, 23, 23, 6)        0         
 ePooling2D)                                                     
                                                                 
 conv2d_5 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_3 (Averag  (None, 9, 9, 16)         0         
 ePooling2D)                                                     
                                                                 
 conv2d_6 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten_1 (Flatten)         (None, 3000)             

In [36]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [38]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/20
1688/1688 [==============================] - 23s 12ms/step - loss: 0.2178 - accuracy: 0.9357 - val_loss: 0.1398 - val_accuracy: 0.9563
Epoch 2/20
1688/1688 [==============================] - 26s 16ms/step - loss: 0.1017 - accuracy: 0.9706 - val_loss: 0.0844 - val_accuracy: 0.9737
Epoch 3/20
1688/1688 [==============================] - 23s 13ms/step - loss: 0.0776 - accuracy: 0.9763 - val_loss: 0.0701 - val_accuracy: 0.9773
Epoch 4/20
1688/1688 [==============================] - 27s 16ms/step - loss: 0.0727 - accuracy: 0.9783 - val_loss: 0.0626 - val_accuracy: 0.9820
Epoch 5/20
1688/1688 [==============================] - 22s 13ms/step - loss: 0.0652 - accuracy: 0.9807 - val_loss: 0.0831 - val_accuracy: 0.9738
Epoch 6/20
1688/1688 [==============================] - 27s 16ms/step - loss: 0.0589 - accuracy: 0.9821 - val_loss: 0.0602 - val_accuracy: 0.9813
Epoch 7/20
1688/1688 [==============================] - 24s 14ms/step - loss: 0.0546 - accuracy: 0.9836 - val_loss: 0.0602 -

In [39]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 [==============================] - 1s 4ms/step - loss: 0.0453 - accuracy: 0.9866


In [40]:
score

[0.04531022161245346, 0.9865999817848206]